---
title: "R Notebook"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---

# change to subject date time

# open data
```{r}
rm(list=ls())

library(ggplot2)
library(reshape2)
library(plyr)
library(dplyr)
library(extrafont)
#font_import()
loadfonts(device = "win")

setwd("~/Projects/SeqLearn/stats")

test_sessions = c(0, 6, 12, 18, 24, 30, 36)

theme_lh <- function () { 
    theme_bw(base_size=18, base_family="Avenir")
}

maxy = 4500 
miny = 500 




#############################

WAVE = 3


if(WAVE == 1){
trialsfile = paste0('../data/archive/trials_table-20190923_1531-Lund1db.csv')
trialsfilefmri = paste0('../data/archive/trials_table-20190802_1727-Lund1fmridb.csv')
}
if(WAVE == 2){
trialsfile = paste0('../data/archive/trials_table-20190923_0848-Lund2db.csv')
trialsfilefmri = paste0('../data/archive/trials_table-20190923_1423-Lund2fmridb.csv')
}
if(WAVE == 3){
trialsfile = paste0('../data/archive/trials_table-20191104_0918-Lund3db.csv')
trialsfilefmri = paste0('../data/archive/trials_table-20190923_1423-Lund2fmridb.csv')
}


trials.table = unique(read.table(trialsfile, sep =';', header = T,quote = "")[-1]) %>% mutate(date_time = paste(username, sess_date, sess_time))
trials.table$username = as.character(trials.table$username)

trials.table.fmri = unique(read.table(trialsfilefmri, sep =';', header = T,quote = "")[-1]) %>% mutate(date_time = paste(username, sess_date, sess_time))
trials.table.fmri$username = as.character(trials.table.fmri$username)


# analyze only these
#include = c("lue1103")
# analyze only these
#exclude = c("lue1101")

# analyze only these
#trials.table = subset(trials.table, username %in% include)
#trials.table = subset(trials.table, !username %in% exclude)

```

Correct and assign groups

Home
```{r}
# RENAME
################
# WAVE 1
################
if(WAVE == 1){
trials.table = subset(trials.table, !(sess_time == "15:55:23.768000" & sess_num == 0 & username == "lue1202"))

trials.table[trials.table$username == "lue1101" & trials.table$sess_num == 1, ]$sess_num = 0
trials.table[trials.table$username == "lue1104" & trials.table$sess_date == "2019-06-06", ]$sess_num = 33
trials.table[trials.table$username == "lue1104" & trials.table$sess_date == "2019-06-07", ]$sess_num = 34
trials.table[trials.table$username == "lue1104" & trials.table$sess_date == "2019-06-08", ]$sess_num = 35

}

################
# WAVE 2
################
if(WAVE == 2){
  # they did less than 2 sessions
  trials.table = subset(trials.table, !username %in% c("lue2204","lue2206","lue2207"))
}

################
# WAVE 3
################
if(WAVE == 3){
  # they did less than 2 sessions
  trials.table = subset(trials.table, !username %in% c("lue3106"))
}

################
# check that the number of trials is correct
# n : number of trials, should be 20 if the session was not interrupted
# cum_trial: counts how many sequences were started, should be 6 for training( paced + unpaced) and 5 for the testing (unpaced trained + untrained)

ntrials = trials.table %>% group_by(username, date_time, sess_num, run, sess_type) %>% dplyr::summarise(n = max(trial, na.rm = T), cum_trial = sum(cumulative_trial == 1)) 
interrupted_times = ntrials$date_time[!(( ntrials$cum_trial == 6 & ntrials$sess_type == "training") | ( ntrials$cum_trial == 5 & ntrials$sess_type == "testing"))]
print("Interrupted sessions")
print(interrupted_times)
trials.table = subset(trials.table, !date_time %in% interrupted_times)
```


FMRI

```{r}

ntrials.fmri = trials.table.fmri %>% group_by(username, date_time, sess_num, run) %>% dplyr::summarise(n = n(), cum_trial = sum(cumulative_trial == 1))

interrupted_times.fmri = ntrials.fmri$date_time[ntrials.fmri$n < max(ntrials.fmri$n)]

print("Interrupted fmri runs")
print(interrupted_times.fmri)
trials.table.fmri = subset(trials.table.fmri, !date_time %in% interrupted_times.fmri)
               
if(WAVE == 1){
  
  dt_exclude = c("lue1203 2019-05-05 10:42:34.981000", "lue1205 2019-04-28 11:02:27")
  #"lue1101 2019-05-04 13:29:27.665000", "lue1103 2019-04-27 14:43:56.336000", 
  #               "lue1103 2019-05-18 14:48:11.918000",  
  #               "lue1106 2019-05-18 16:06:27.653000", "lue1201 2019-04-28 17:18:59.337000", 
  trials.table.fmri = subset(trials.table.fmri, !date_time %in% dt_exclude)
  
  
  #task not synced, use??
  #trials.table.fmri = subset(trials.table.fmri, !(username == "lue1101" & sess_num == 6 ))
  #trials.table.fmri = subset(trials.table.fmri, !(username == "lue1103" & sess_num == 6 & run == 1))
  

}


```

Output
```{r}
# Save clean data
write.table(trials.table, file = paste0('../data/archive/clean/trials_table_Lund', WAVE, '_clean.csv'), sep = ";", row.names = F)
#  write.table(trials.table.fmri, file = '../data/archive/trials_table_Lund', WAVE, 'fmri_clean.csv')


```


# Number of sessions of each subject
```{r fig.width=25, fig.asp=0.7}
trials.sess = trials.table %>% group_by(username, sess_num, sess_date, sess_time) %>% dplyr::summarise( n_sess = n() > 0) %>% 
  group_by(username, sess_num, sess_date) %>% dplyr::summarise( n_sess = sum(n_sess))

plot.sess = ggplot(trials.sess, aes(x = sess_num, y = n_sess, group = username)) + geom_line(lwd=0.5) + geom_point(size=1.5) + facet_grid( username ~ .) + theme_lh() + theme(legend.position="none") 

print(plot.sess)

trials.sess.fmri = trials.table.fmri %>% group_by(username, sess_num, sess_date, sess_time) %>% dplyr::summarise( n_sess = n() > 0) %>% 
  group_by(username, sess_num, sess_date) %>% dplyr::summarise( n_sess = sum(n_sess))

plot.sess.fmri = ggplot(trials.sess.fmri, aes(x = sess_num, y = n_sess, group = username)) + geom_line(lwd=0.5) + geom_point(size=1.5) + geom_hline(yintercept = 5, lty = 2) + facet_grid( username ~ .) + theme_lh() + theme(legend.position="none", axis.text.x = element_text(angle=90)) + ylab("Number of runs")

print(plot.sess.fmri)

```

Name groups

```{r}
trials.table$group = "Experimental"
trials.table$group[grep("lue.2", trials.table$username)] = "Control"
trials.table.fmri$group = "Experimental"
trials.table.fmri$group[grep("lue.2", trials.table.fmri$username)] = "Control"
```

Performance
```{r fig.width=25, fig.asp=0.7}


ok_trials = subset(trials.table, accuracy == 1)
unpaced_trials = subset(trials.table, paced == 0 & trial_type != "missed")
paced_trials = subset(trials.table, paced == 1 & trial_type != "missed")
ok_unpaced_trials = subset(unpaced_trials, accuracy == 1)
ok_paced_trials = subset(paced_trials, accuracy == 1)
                      
plot.MT = ggplot(ok_unpaced_trials, aes(x = trial, y = MT, col = as.factor(seq_train), group = true_sequence)) + geom_line(lwd=0.5) + geom_point(size=0.7) + ylim(miny, maxy) +  facet_grid( username ~ sess_num) + theme_lh() + theme(legend.position="none", axis.text.x = element_text( size = 10, angle = 90))

plot.MT.paced = ggplot(ok_paced_trials, aes(x = trial, y = MT, col = as.factor(seq_train), group = true_sequence)) + geom_line(lwd=0.5) + geom_point(size=0.7) + ylim(miny, maxy) + facet_grid( username ~ sess_num) + theme_lh() + theme(legend.position="none", axis.text.x = element_text( size = 10, angle = 90))

plot.MT.paced.hist = ggplot(ok_paced_trials, aes(x = MT, col = as.factor(seq_train), group = true_sequence)) + geom_histogram(bins = 50) + facet_grid(  username ~ . ) + theme_lh() + theme(legend.position="none")
 
print(plot.MT)
print(plot.MT.paced)
#print(plot.MT.paced.hist)

```



Mean performance
```{r fig.width=25, fig.asp=0.4}

# consider only last trials 
last_trials = subset(ok_unpaced_trials, trial > 10) %>% 
  group_by(username, sess_num, true_sequence, seq_train, group) %>% 
  dplyr::summarise(meanMT = mean(MT), sdMT = sd(MT))

plot.meanMT = ggplot(last_trials, aes(x = sess_num, y = meanMT, group = true_sequence, col = as.factor(seq_train))) + geom_line(lwd=1) + geom_point() + facet_grid( . ~ username ) + theme(legend.position="bottom") + theme_lh()

print(plot.meanMT)

plot.meanMT = ggplot(subset(last_trials, group == "Experimental" & seq_train == "trained"), aes(x = sess_num, y = meanMT, group = true_sequence, col = as.factor(true_sequence))) + geom_line(lwd=1) + geom_point() + facet_grid( . ~ username ) + theme(legend.position="none") + theme_lh() + xlab("Session") + ylab("Mean MT (ms)")

print(plot.meanMT)

# aggregate within participant and compare participants

last_trials.user = last_trials %>% 
  group_by(username, sess_num, seq_train, group) %>% 
  dplyr::summarise(meanMT = mean(meanMT), sdMT = mean(sdMT))

plot.meanMT.user = ggplot(last_trials.user, aes(x = sess_num, y = meanMT, col = username, lty = as.factor(seq_train), shape = as.factor(seq_train))) + geom_line(lwd=1) + geom_point(size = 3) + facet_grid( group ~ seq_train) + theme_lh()

print(plot.meanMT.user)

plot.sdMT.user = ggplot(last_trials.user, aes(x = sess_num, y = sdMT, col = username, lty = as.factor(seq_train), shape = as.factor(seq_train))) + geom_line(lwd=1) + geom_point(size = 3) + facet_grid( group ~ seq_train) + theme_lh()

print(plot.sdMT.user)


# aggregate within sequence 
last_trials.sequence = last_trials %>% 
  group_by(true_sequence, username, sess_num, seq_train, group) %>% 
  dplyr::summarise(meanMT = mean(meanMT), sdMT = mean(sdMT))

plot.meanMT.sequence = ggplot(last_trials.sequence, aes(x = sess_num, y = meanMT, group = username, lty = as.factor(seq_train), col = username)) + geom_line(lwd=1) + geom_point(size = 3) + facet_grid( seq_train ~ true_sequence ) + theme_lh() + theme(legend.position="bottom") 

print(plot.meanMT.sequence)

# plot mean for each group
plot.meanMT.group = ggplot(last_trials.user, aes(x = sess_num, y = meanMT, group = username, col = as.factor(seq_train)))  + geom_vline(xintercept = test_sessions, lty = 2) +  geom_smooth(aes(group=as.factor(seq_train)))  + theme_lh() + theme( legend.position="bottom") + xlab('Session') + ylab('Movement duration mean (ms)') + facet_grid(.~group) 

print(plot.meanMT.group)

plot.meanMT.group2 = ggplot(last_trials.user, aes(x = sess_num, y = meanMT, group = username, col = group))  + geom_vline(xintercept = test_sessions, lty = 2) +  geom_smooth(aes(group=as.factor(group)))  + theme_lh() + theme( legend.position="bottom") + xlab('Session') + ylab('Movement duration mean (ms)') + facet_grid(.~seq_train) 

print(plot.meanMT.group2)


plot.sdMT.group = ggplot(last_trials.user, aes(x = sess_num, y = sdMT, group = username, col = as.factor(seq_train))) + geom_vline(xintercept = test_sessions, lty = 2) +  geom_smooth(aes(group=as.factor(seq_train)))  + theme_lh() + theme( legend.position="bottom") + xlab('Session') + ylab('Movement duration SD (ms)') + facet_grid(.~group)

print(plot.sdMT.group)

```

Savings

```{r fig.width=15, fig.asp=0.7}
last.5 = subset(ok_unpaced_trials, trial > 15 ) %>% 
  group_by(username, sess_num, true_sequence, seq_train, group) %>% 
  dplyr::summarise(meanMT = mean(MT), sdMT = sd(MT))
first.5 = subset(ok_unpaced_trials, trial <=5) %>% 
  group_by(username, sess_num, true_sequence, seq_train, group) %>% 
  dplyr::summarise(meanMT = mean(MT), sdMT = sd(MT))

savings = merge(first.5, last.5, by = c("username", "sess_num", "true_sequence", "seq_train", "group"), suffix = c(".first", ".last")) %>% mutate(meanMT = (meanMT.first - meanMT.last)) %>%  group_by(username, sess_num, seq_train, group) %>% dplyr::summarise(meanMT = mean(meanMT))

plot.savings = ggplot(savings, aes(x = sess_num, y = meanMT, group = username, col = as.factor(seq_train))) + geom_point() + geom_line() + theme_lh() + theme( legend.position="none") + xlab('Session') + ylab('Movement duration (ms)') + facet_grid(as.factor(seq_train) ~ group)

print(plot.savings)

plot.savings.group = ggplot(savings, aes(x = sess_num, y = meanMT, group = username, col = as.factor(seq_train))) + geom_vline(xintercept = test_sessions, lty = 2) +  geom_smooth(aes(group=as.factor(seq_train)))  + theme_lh() + theme( legend.position="none") + xlab('Session') + ylab('Movement duration (ms)') + facet_grid(.~group)

print(plot.savings.group)

plot.summary = ggplot(subset(savings, sess_num%% 6 == 0), aes(x = group, y = meanMT, fill = group)) + geom_boxplot() + theme_lh() + theme(legend.title=element_blank()) + xlab('Session') + ylab('Movement duration  (ms)') + facet_grid( seq_train~ as.factor(sess_num)) + theme_lh()
print(plot.summary)


```


As clusters
```{r fig.width=8, fig.asp=1.5}
trials_arr = acast(subset(last_trials.sequence, seq_train == "trained" & group == "Experimental"),  sess_num ~ true_sequence ~ username, value.var = "meanMT")
trials_mat = do.call(cbind, alply(trials_arr, 3))

colnames(trials_mat) = sapply(dimnames(trials_arr)[[3]], function(x) rep(x, dim(trials_arr)[2]))
distances = cor(trials_mat, use = "pairwise.complete.obs") 
#distances = dist(trials_mat)
distances[lower.tri(distances)] = NA
distances.melt = subset(melt(distances, na.rm = T), value != 1) 
distances.melt$type = "within"
distances.melt$type[distances.melt$Var1 != distances.melt$Var2 ] = "between"

par(mar = c(5, 5, 5, 5))
boxplot(value ~ type, data = distances.melt, ylab = "Correlation", cex.axis = 2, cex.lab = 2)
#print(ggplot(distances.melt, aes(Var1,group = type, col = type)) + geom_histogram())
wilcox.test(value ~ type, data = distances.melt, method = "")
```



Wrong trials 

```{r fig.width=11, fig.asp=1.2}

unpaced_trials.wrong = unpaced_trials %>% 
  group_by(username, sess_num, true_sequence, seq_train) %>% 
  dplyr::summarise(wrong_trials = sum(accuracy < 1))

paced_trials.wrong = paced_trials %>% 
  group_by(username, sess_num, true_sequence, seq_train) %>% 
  dplyr::summarise(wrong_trials = sum(accuracy < 1))

plot.unpaced.wrong = ggplot(unpaced_trials.wrong, aes(x = sess_num, y = wrong_trials, col = true_sequence, group = true_sequence, lty = as.factor(seq_train))) + geom_line(lwd=1) + geom_point() + facet_grid( username ~ .) + theme(legend.position="none") + theme_lh()

plot.paced.wrong = ggplot(paced_trials.wrong, aes(x = sess_num, y = wrong_trials, col = true_sequence, group = true_sequence, lty = as.factor(seq_train))) + geom_line(lwd=1) + geom_point() + facet_grid( username ~ .) + theme(legend.position="none") + theme_lh()

print(plot.unpaced.wrong)
print(plot.paced.wrong)

```


Trained vs untrained
```{r fig.width=20, fig.asp=0.6}


# remove average for each subject
mean.user.sequence.demeaned = subset(last_trials.sequence, sess_num%% 6 == 0) %>% group_by(username) %>% mutate(meanMT = meanMT)
#mutate(meanMT = meanMT - mean(meanMT))
plot.summary = ggplot(mean.user.sequence.demeaned, aes(x = group, y = meanMT, fill = seq_train)) + geom_boxplot() + theme_lh() + theme(legend.title=element_blank()) + xlab('Session') + ylab('Movement duration mean (ms)') + facet_grid( .~ as.factor(sess_num)) + theme_lh()
print(plot.summary)

```



Missed trials 

```{r fig.width=11, fig.asp=0.8}

unpaced_trials.missed = subset(trials.table, paced == 0 & trial_type == "missed") %>% 
  group_by(username, sess_num, true_sequence, seq_train) %>% 
  dplyr::summarise(missed_trials = n())

paced_trials.missed = subset(trials.table, paced == 1 & trial_type == "missed") %>% 
  group_by(username, sess_num, true_sequence, seq_train) %>% 
  dplyr::summarise(missed_trials = n())

plot.unpaced.missed = ggplot(unpaced_trials.missed, aes(x = sess_num, y = missed_trials, col = true_sequence, group = true_sequence, lty = as.factor(seq_train))) + geom_line(lwd=1) + geom_point() + facet_grid( username ~ .) + theme(legend.position="none")

plot.paced.missed = ggplot(paced_trials.missed, aes(x = sess_num, y = missed_trials, col = true_sequence, group = true_sequence, lty = as.factor(seq_train))) + geom_line(lwd=1) + geom_point() + facet_grid( username ~ .) + theme(legend.position="none")

print(plot.unpaced.missed)
#print(plot.paced.missed)

```


Session duration
```{r fig.width=11, fig.asp=0.6}
plot.duration = ggplot(trials.table, aes(x = sess_num, y = global_clock/60, col = username, group = username)) + 
  stat_summary(fun.y = max, geom = "line", lwd = 1) +  stat_summary(fun.y = max, geom = "point") + ylab("Session duration") + xlab("Session") +  facet_grid(.~group) + theme_lh()

print(plot.duration)

```


Dates and times
```{r fig.width=11, fig.asp=0.8}

trials.times = trials.table %>% mutate(sess_date = as.Date(sess_date), sess_time = as.POSIXct(sess_time, format="%H:%M:%S")) %>% group_by(username, sess_num, sess_date, sess_time, sess_type) %>% sample_n(1) 
#kip1 = grep('kip1', trials.times$username)
#trials.times =trials.times[kip1, ]
plot.dates = ggplot(trials.times, aes(x = sess_num, y = sess_date, col = username, group = username)) + geom_line() + geom_point() + xlab("Session number") + ylab("Session date") + scale_y_date()

print(plot.dates)

table(trials.times$username)

plot.times = ggplot(trials.times, aes(x = sess_num, y = sess_time)) + geom_line() + geom_point() + xlab("Session number") + ylab("Session time") + facet_grid( . ~ username) + theme_lh()
print(plot.times)

```

```{r fig.width=18, fig.asp=0.7}

paced_trials = subset(trials.table.fmri, paced == 1 & trial_type != "missed" & sess_type == "fmri")

plot.MT.paced = ggplot(paced_trials, aes(x = block, y = accuracy, col = as.factor(seq_train), group = true_sequence)) + geom_line(lwd=1) + geom_point() + facet_grid( username ~ sess_num + run) + theme(legend.position="none") + theme_lh()

plot.MT.paced.hist = ggplot(paced_trials, aes(accuracy)) + geom_histogram(bins = 6) + facet_grid( username ~ sess_num + run) + theme(legend.position="none") + theme_lh()

correct_sess_trials = paced_trials %>%
  group_by(username, sess_num, seq_train, group) %>% 
  dplyr::summarise(correct = sum(accuracy==1))

plot.correct.sess = ggplot(correct_sess_trials, aes(x = sess_num, y = correct, col = username)) + geom_line() +  geom_point()  + theme(legend.position="none") + theme_lh() + facet_grid(. ~ group + seq_train)

correct_run_trials = paced_trials %>%
  group_by(username, seq_train, sess_num, group, run) %>% 
  dplyr::summarise(correct = sum(accuracy==1))

plot.correct.run = ggplot(correct_run_trials, aes(x = run, y = correct, col = username)) + geom_line() +  geom_point()  + theme(legend.position="none") + facet_grid(group + seq_train ~sess_num ) + theme_lh() 

#plot.MT.paced.hist = ggplot(ok_paced_trials, aes(x = MT, col = as.factor(seq_train), group = true_sequence)) + geom_histogram(bins = 50) + facet_grid(  username ~ . ) + theme(legend.position="none") + theme_lh()

print(plot.MT.paced)
print(plot.MT.paced.hist)
print(plot.correct.sess)
print(plot.correct.run)

```

```{r fig.width=18, fig.asp=0.6}

mean_paced_trials = subset(paced_trials, accuracy == 1) %>% 
  group_by(username, sess_num, true_sequence, seq_train, group) %>% 
  dplyr::summarise(meanMT = mean(MT), sdMT = sd(MT)) %>% 
  group_by(username, sess_num, seq_train, group) %>% 
  dplyr::summarise(meanMT = mean(meanMT), sdMT = mean(sdMT))

# plot mean for each group

plot.meanMT.user = ggplot(mean_paced_trials, aes(x = sess_num, y = meanMT, col = username, lty = as.factor(seq_train), shape = as.factor(seq_train))) + geom_line(lwd=1) + geom_point(size = 3) + facet_grid( group ~ seq_train) + theme_lh()

print(plot.meanMT.user)

plot.meanMT.group = ggplot(mean_paced_trials, aes(x = group, y = meanMT, fill = group)) + geom_boxplot() + theme_lh() + theme(legend.title=element_blank()) + xlab('Session') + ylab('Movement duration mean (ms)') + facet_grid( seq_train~ as.factor(sess_num)) + theme_lh()

print(plot.meanMT.group)

plot.sdMT.group = ggplot(mean_paced_trials, aes(x = group, y = meanMT, fill = group)) + geom_boxplot() + theme_lh() + theme(legend.title=element_blank()) + xlab('Session') + ylab('Movement duration SD (ms)') + facet_grid( seq_train~ as.factor(sess_num)) + theme_lh()

print(plot.sdMT.group)

```

```{r}
library(lme4)
library(lmerTest)

coefs = NULL
pvalues = NULL
last_trials$seq_train2 = relevel(last_trials$seq_train, ref = "trained" )

for (i in test_sessions){
  MT.model = lmer(meanMT ~ group*seq_train2 + (1|username), data = subset(last_trials, sess_num == i))
#  MT.model = lmer(meanMT ~ group + (1|username), data = subset(last_trials, seq_train == "untrained" & sess_num == i))
  coefs = cbind(coefs, fixef(MT.model))
  pvalues = cbind(pvalues, summary(MT.model)$coefficients[, "Pr(>|t|)"])
  print(summary(MT.model))
  print("----------------------------------------------------------------------")
}

colnames(coefs) = test_sessions

plot(test_sessions, coefs[2, ], type = "both", pch = ifelse(pvalues[2, ] < 0.05, 8, 20))
plot(test_sessions, coefs[3, ], type = "both", pch = ifelse(pvalues[3, ] < 0.05, 8, 20))
plot(test_sessions, coefs[4, ], type = "both", pch = ifelse(pvalues[4, ] < 0.05, 8, 20))

```

```{r}

last_trials$sess_dem = last_trials$sess_num - 12
last_trials$sess_dem2 = last_trials$sess_dem^2
#MT.model = lmer(meanMT ~ group*seq_train2*sess_dem + group*seq_train2*sess_dem2 + (1 + sess_dem + sess_dem2|username), data = subset(last_trials, sess_num %in% test_sessions))
#summary(MT.model)
#coefs = fixef(MT.model)
#plot(last_trials$sess_num, coefs["groupExperimental:seq_train2untrained"] + coefs["groupExperimental:seq_train2untrained:sess_dem"]*last_trials$sess_dem + coefs["groupExperimental:seq_train2untrained:sess_dem2"]*last_trials$sess_dem2, pch = 20, ylab = "Near transfer effect" )

untrained_trials = subset(last_trials, seq_train == "untrained")
MT.model = lmer(meanMT ~ group*sess_dem + group*sess_dem2 + (1|username), data = untrained_trials)
summary(MT.model)
coefs = fixef(MT.model)
plot(untrained_trials$sess_num, coefs["groupExperimental"] + coefs["groupExperimental:sess_dem"]*untrained_trials$sess_dem + coefs["groupExperimental:sess_dem2"]*untrained_trials$sess_dem2, pch = 20, ylab = "Near transfer effect", xlab = "Session")

```